// This file is generated by the effect-codex-app-server package. Do not edit manually.
// Upstream protocol ref: 678157acaa819d5510adfe359abb5d0392cfe461

import * as CodexSchema from "./schema.gen.ts";

export const SERVER_NOTIFICATION_METHODS = {
  error: "error",
  "thread/started": "thread/started",
  "thread/status/changed": "thread/status/changed",
  "thread/archived": "thread/archived",
  "thread/deleted": "thread/deleted",
  "thread/unarchived": "thread/unarchived",
  "thread/closed": "thread/closed",
  "skills/changed": "skills/changed",
  "thread/name/updated": "thread/name/updated",
  "thread/goal/updated": "thread/goal/updated",
  "thread/goal/cleared": "thread/goal/cleared",
  "thread/environment/connected": "thread/environment/connected",
  "thread/environment/disconnected": "thread/environment/disconnected",
  "thread/settings/updated": "thread/settings/updated",
  "thread/tokenUsage/updated": "thread/tokenUsage/updated",
  "turn/started": "turn/started",
  "hook/started": "hook/started",
  "turn/completed": "turn/completed",
  "hook/completed": "hook/completed",
  "turn/diff/updated": "turn/diff/updated",
  "turn/plan/updated": "turn/plan/updated",
  "item/started": "item/started",
  "item/autoApprovalReview/started": "item/autoApprovalReview/started",
  "item/autoApprovalReview/completed": "item/autoApprovalReview/completed",
  "item/completed": "item/completed",
  "rawResponseItem/completed": "rawResponseItem/completed",
  "rawResponse/completed": "rawResponse/completed",
  "item/agentMessage/delta": "item/agentMessage/delta",
  "item/plan/delta": "item/plan/delta",
  "command/exec/outputDelta": "command/exec/outputDelta",
  "process/outputDelta": "process/outputDelta",
  "process/exited": "process/exited",
  "item/commandExecution/outputDelta": "item/commandExecution/outputDelta",
  "item/commandExecution/terminalInteraction": "item/commandExecution/terminalInteraction",
  "item/fileChange/outputDelta": "item/fileChange/outputDelta",
  "item/fileChange/patchUpdated": "item/fileChange/patchUpdated",
  "serverRequest/resolved": "serverRequest/resolved",
  "item/mcpToolCall/progress": "item/mcpToolCall/progress",
  "mcpServer/oauthLogin/completed": "mcpServer/oauthLogin/completed",
  "mcpServer/startupStatus/updated": "mcpServer/startupStatus/updated",
  "account/updated": "account/updated",
  "account/rateLimits/updated": "account/rateLimits/updated",
  "app/list/updated": "app/list/updated",
  "remoteControl/status/changed": "remoteControl/status/changed",
  "externalAgentConfig/import/progress": "externalAgentConfig/import/progress",
  "externalAgentConfig/import/completed": "externalAgentConfig/import/completed",
  "fs/changed": "fs/changed",
  "item/reasoning/summaryTextDelta": "item/reasoning/summaryTextDelta",
  "item/reasoning/summaryPartAdded": "item/reasoning/summaryPartAdded",
  "item/reasoning/textDelta": "item/reasoning/textDelta",
  "thread/compacted": "thread/compacted",
  "model/rerouted": "model/rerouted",
  "model/verification": "model/verification",
  "turn/moderationMetadata": "turn/moderationMetadata",
  "model/safetyBuffering/updated": "model/safetyBuffering/updated",
  warning: "warning",
  guardianWarning: "guardianWarning",
  deprecationNotice: "deprecationNotice",
  configWarning: "configWarning",
  "fuzzyFileSearch/sessionUpdated": "fuzzyFileSearch/sessionUpdated",
  "fuzzyFileSearch/sessionCompleted": "fuzzyFileSearch/sessionCompleted",
  "thread/realtime/started": "thread/realtime/started",
  "thread/realtime/itemAdded": "thread/realtime/itemAdded",
  "thread/realtime/transcript/delta": "thread/realtime/transcript/delta",
  "thread/realtime/transcript/done": "thread/realtime/transcript/done",
  "thread/realtime/outputAudio/delta": "thread/realtime/outputAudio/delta",
  "thread/realtime/sdp": "thread/realtime/sdp",
  "thread/realtime/error": "thread/realtime/error",
  "thread/realtime/closed": "thread/realtime/closed",
  "windows/worldWritableWarning": "windows/worldWritableWarning",
  "windowsSandbox/setupCompleted": "windowsSandbox/setupCompleted",
  "account/login/completed": "account/login/completed",
} as const;

export type ClientRequestMethod = keyof typeof CLIENT_REQUEST_PARAMS;
export type ClientNotificationMethod = keyof typeof CLIENT_NOTIFICATION_PARAMS;
export type ServerRequestMethod = keyof typeof SERVER_REQUEST_PARAMS;
export type ServerNotificationMethod = keyof typeof SERVER_NOTIFICATION_METHODS;

export interface ClientRequestParamsByMethod {
  readonly initialize: CodexSchema.V1InitializeParams;
  readonly "thread/start": CodexSchema.V2ThreadStartParams;
  readonly "thread/resume": CodexSchema.V2ThreadResumeParams;
  readonly "thread/compact/start": CodexSchema.V2ThreadCompactStartParams;
  readonly "thread/rollback": CodexSchema.V2ThreadRollbackParams;
  readonly "thread/read": CodexSchema.V2ThreadReadParams;
  readonly "skills/list": CodexSchema.V2SkillsListParams;
  readonly "turn/start": CodexSchema.V2TurnStartParams;
  readonly "turn/interrupt": CodexSchema.V2TurnInterruptParams;
  readonly "model/list": CodexSchema.V2ModelListParams;
  readonly "config/mcpServer/reload": undefined;
  readonly "account/rateLimits/read": undefined;
  readonly "account/rateLimitResetCredit/consume": CodexSchema.V2ConsumeAccountRateLimitResetCreditParams;
  readonly "feedback/upload": CodexSchema.V2FeedbackUploadParams;
  readonly "account/read": CodexSchema.V2GetAccountParams;
}

export interface ClientRequestResponsesByMethod {
  readonly initialize: CodexSchema.V1InitializeResponse;
  readonly "thread/start": CodexSchema.V2ThreadStartResponse;
  readonly "thread/resume": CodexSchema.V2ThreadResumeResponse;
  readonly "thread/compact/start": CodexSchema.V2ThreadCompactStartResponse;
  readonly "thread/rollback": CodexSchema.V2ThreadRollbackResponse;
  readonly "thread/read": CodexSchema.V2ThreadReadResponse;
  readonly "skills/list": CodexSchema.V2SkillsListResponse;
  readonly "turn/start": CodexSchema.V2TurnStartResponse;
  readonly "turn/interrupt": CodexSchema.V2TurnInterruptResponse;
  readonly "model/list": CodexSchema.V2ModelListResponse;
  readonly "config/mcpServer/reload": CodexSchema.V2McpServerRefreshResponse;
  readonly "account/rateLimits/read": CodexSchema.V2GetAccountRateLimitsResponse;
  readonly "account/rateLimitResetCredit/consume": CodexSchema.V2ConsumeAccountRateLimitResetCreditResponse;
  readonly "feedback/upload": CodexSchema.V2FeedbackUploadResponse;
  readonly "account/read": CodexSchema.V2GetAccountResponse;
}

export interface ClientNotificationParamsByMethod {
  readonly initialized: undefined;
}

export interface ServerRequestParamsByMethod {
  readonly "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalParams;
  readonly "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalParams;
  readonly "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputParams;
  readonly "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestParams;
  readonly "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalParams;
  readonly "item/tool/call": CodexSchema.DynamicToolCallParams;
  readonly "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshParams;
  readonly "attestation/generate": CodexSchema.AttestationGenerateParams;
  readonly applyPatchApproval: CodexSchema.ApplyPatchApprovalParams;
  readonly execCommandApproval: CodexSchema.ExecCommandApprovalParams;
}

export interface ServerRequestResponsesByMethod {
  readonly "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalResponse;
  readonly "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalResponse;
  readonly "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputResponse;
  readonly "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestResponse;
  readonly "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalResponse;
  readonly "item/tool/call": CodexSchema.DynamicToolCallResponse;
  readonly "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshResponse;
  readonly "attestation/generate": CodexSchema.AttestationGenerateResponse;
  readonly applyPatchApproval: CodexSchema.ApplyPatchApprovalResponse;
  readonly execCommandApproval: CodexSchema.ExecCommandApprovalResponse;
}

export interface ServerNotificationParamsByMethod {
  readonly error: CodexSchema.V2ErrorNotification;
  readonly "thread/started": CodexSchema.V2ThreadStartedNotification;
  readonly "thread/status/changed": CodexSchema.V2ThreadStatusChangedNotification;
  readonly "thread/archived": CodexSchema.V2ThreadArchivedNotification;
  readonly "thread/deleted": CodexSchema.V2ThreadDeletedNotification;
  readonly "thread/unarchived": CodexSchema.V2ThreadUnarchivedNotification;
  readonly "thread/closed": CodexSchema.V2ThreadClosedNotification;
  readonly "skills/changed": CodexSchema.V2SkillsChangedNotification;
  readonly "thread/name/updated": CodexSchema.V2ThreadNameUpdatedNotification;
  readonly "thread/goal/updated": CodexSchema.V2ThreadGoalUpdatedNotification;
  readonly "thread/goal/cleared": CodexSchema.V2ThreadGoalClearedNotification;
  readonly "thread/environment/connected": CodexSchema.V2EnvironmentConnectionNotification;
  readonly "thread/environment/disconnected": CodexSchema.V2EnvironmentConnectionNotification;
  readonly "thread/settings/updated": CodexSchema.V2ThreadSettingsUpdatedNotification;
  readonly "thread/tokenUsage/updated": CodexSchema.V2ThreadTokenUsageUpdatedNotification;
  readonly "turn/started": CodexSchema.V2TurnStartedNotification;
  readonly "hook/started": CodexSchema.V2HookStartedNotification;
  readonly "turn/completed": CodexSchema.V2TurnCompletedNotification;
  readonly "hook/completed": CodexSchema.V2HookCompletedNotification;
  readonly "turn/diff/updated": CodexSchema.V2TurnDiffUpdatedNotification;
  readonly "turn/plan/updated": CodexSchema.V2TurnPlanUpdatedNotification;
  readonly "item/started": CodexSchema.V2ItemStartedNotification;
  readonly "item/autoApprovalReview/started": CodexSchema.V2ItemGuardianApprovalReviewStartedNotification;
  readonly "item/autoApprovalReview/completed": CodexSchema.V2ItemGuardianApprovalReviewCompletedNotification;
  readonly "item/completed": CodexSchema.V2ItemCompletedNotification;
  readonly "rawResponseItem/completed": CodexSchema.V2RawResponseItemCompletedNotification;
  readonly "rawResponse/completed": CodexSchema.V2RawResponseCompletedNotification;
  readonly "item/agentMessage/delta": CodexSchema.V2AgentMessageDeltaNotification;
  readonly "item/plan/delta": CodexSchema.V2PlanDeltaNotification;
  readonly "command/exec/outputDelta": CodexSchema.V2CommandExecOutputDeltaNotification;
  readonly "process/outputDelta": CodexSchema.V2ProcessOutputDeltaNotification;
  readonly "process/exited": CodexSchema.V2ProcessExitedNotification;
  readonly "item/commandExecution/outputDelta": CodexSchema.V2CommandExecutionOutputDeltaNotification;
  readonly "item/commandExecution/terminalInteraction": CodexSchema.V2TerminalInteractionNotification;
  readonly "item/fileChange/outputDelta": CodexSchema.V2FileChangeOutputDeltaNotification;
  readonly "item/fileChange/patchUpdated": CodexSchema.V2FileChangePatchUpdatedNotification;
  readonly "serverRequest/resolved": CodexSchema.V2ServerRequestResolvedNotification;
  readonly "item/mcpToolCall/progress": CodexSchema.V2McpToolCallProgressNotification;
  readonly "mcpServer/oauthLogin/completed": CodexSchema.V2McpServerOauthLoginCompletedNotification;
  readonly "mcpServer/startupStatus/updated": CodexSchema.V2McpServerStatusUpdatedNotification;
  readonly "account/updated": CodexSchema.V2AccountUpdatedNotification;
  readonly "account/rateLimits/updated": CodexSchema.V2AccountRateLimitsUpdatedNotification;
  readonly "app/list/updated": CodexSchema.V2AppListUpdatedNotification;
  readonly "remoteControl/status/changed": CodexSchema.V2RemoteControlStatusChangedNotification;
  readonly "externalAgentConfig/import/progress": CodexSchema.V2ExternalAgentConfigImportProgressNotification;
  readonly "externalAgentConfig/import/completed": CodexSchema.V2ExternalAgentConfigImportCompletedNotification;
  readonly "fs/changed": CodexSchema.V2FsChangedNotification;
  readonly "item/reasoning/summaryTextDelta": CodexSchema.V2ReasoningSummaryTextDeltaNotification;
  readonly "item/reasoning/summaryPartAdded": CodexSchema.V2ReasoningSummaryPartAddedNotification;
  readonly "item/reasoning/textDelta": CodexSchema.V2ReasoningTextDeltaNotification;
  readonly "thread/compacted": CodexSchema.V2ContextCompactedNotification;
  readonly "model/rerouted": CodexSchema.V2ModelReroutedNotification;
  readonly "model/verification": CodexSchema.V2ModelVerificationNotification;
  readonly "turn/moderationMetadata": CodexSchema.V2TurnModerationMetadataNotification;
  readonly "model/safetyBuffering/updated": CodexSchema.V2ModelSafetyBufferingUpdatedNotification;
  readonly warning: CodexSchema.V2WarningNotification;
  readonly guardianWarning: CodexSchema.V2GuardianWarningNotification;
  readonly deprecationNotice: CodexSchema.V2DeprecationNoticeNotification;
  readonly configWarning: CodexSchema.V2ConfigWarningNotification;
  readonly "fuzzyFileSearch/sessionUpdated": CodexSchema.FuzzyFileSearchSessionUpdatedNotification;
  readonly "fuzzyFileSearch/sessionCompleted": CodexSchema.FuzzyFileSearchSessionCompletedNotification;
  readonly "thread/realtime/started": CodexSchema.V2ThreadRealtimeStartedNotification;
  readonly "thread/realtime/itemAdded": CodexSchema.V2ThreadRealtimeItemAddedNotification;
  readonly "thread/realtime/transcript/delta": CodexSchema.V2ThreadRealtimeTranscriptDeltaNotification;
  readonly "thread/realtime/transcript/done": CodexSchema.V2ThreadRealtimeTranscriptDoneNotification;
  readonly "thread/realtime/outputAudio/delta": CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification;
  readonly "thread/realtime/sdp": CodexSchema.V2ThreadRealtimeSdpNotification;
  readonly "thread/realtime/error": CodexSchema.V2ThreadRealtimeErrorNotification;
  readonly "thread/realtime/closed": CodexSchema.V2ThreadRealtimeClosedNotification;
  readonly "windows/worldWritableWarning": CodexSchema.V2WindowsWorldWritableWarningNotification;
  readonly "windowsSandbox/setupCompleted": CodexSchema.V2WindowsSandboxSetupCompletedNotification;
  readonly "account/login/completed": CodexSchema.V2AccountLoginCompletedNotification;
}

export const CLIENT_REQUEST_PARAMS = {
  initialize: CodexSchema.V1InitializeParams,
  "thread/start": CodexSchema.V2ThreadStartParams,
  "thread/resume": CodexSchema.V2ThreadResumeParams,
  "thread/compact/start": CodexSchema.V2ThreadCompactStartParams,
  "thread/rollback": CodexSchema.V2ThreadRollbackParams,
  "thread/read": CodexSchema.V2ThreadReadParams,
  "skills/list": CodexSchema.V2SkillsListParams,
  "turn/start": CodexSchema.V2TurnStartParams,
  "turn/interrupt": CodexSchema.V2TurnInterruptParams,
  "model/list": CodexSchema.V2ModelListParams,
  "config/mcpServer/reload": undefined,
  "account/rateLimits/read": undefined,
  "account/rateLimitResetCredit/consume": CodexSchema.V2ConsumeAccountRateLimitResetCreditParams,
  "feedback/upload": CodexSchema.V2FeedbackUploadParams,
  "account/read": CodexSchema.V2GetAccountParams,
} as const;

export const CLIENT_REQUEST_RESPONSES = {
  initialize: CodexSchema.V1InitializeResponse,
  "thread/start": CodexSchema.V2ThreadStartResponse,
  "thread/resume": CodexSchema.V2ThreadResumeResponse,
  "thread/compact/start": CodexSchema.V2ThreadCompactStartResponse,
  "thread/rollback": CodexSchema.V2ThreadRollbackResponse,
  "thread/read": CodexSchema.V2ThreadReadResponse,
  "skills/list": CodexSchema.V2SkillsListResponse,
  "turn/start": CodexSchema.V2TurnStartResponse,
  "turn/interrupt": CodexSchema.V2TurnInterruptResponse,
  "model/list": CodexSchema.V2ModelListResponse,
  "config/mcpServer/reload": CodexSchema.V2McpServerRefreshResponse,
  "account/rateLimits/read": CodexSchema.V2GetAccountRateLimitsResponse,
  "account/rateLimitResetCredit/consume": CodexSchema.V2ConsumeAccountRateLimitResetCreditResponse,
  "feedback/upload": CodexSchema.V2FeedbackUploadResponse,
  "account/read": CodexSchema.V2GetAccountResponse,
} as const;

export const CLIENT_NOTIFICATION_PARAMS = {
  initialized: undefined,
} as const;

export const SERVER_REQUEST_PARAMS = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalParams,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalParams,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputParams,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestParams,
  "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalParams,
  "item/tool/call": CodexSchema.DynamicToolCallParams,
  "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshParams,
  "attestation/generate": CodexSchema.AttestationGenerateParams,
  applyPatchApproval: CodexSchema.ApplyPatchApprovalParams,
  execCommandApproval: CodexSchema.ExecCommandApprovalParams,
} as const;

export const SERVER_REQUEST_RESPONSES = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalResponse,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalResponse,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputResponse,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestResponse,
  "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalResponse,
  "item/tool/call": CodexSchema.DynamicToolCallResponse,
  "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshResponse,
  "attestation/generate": CodexSchema.AttestationGenerateResponse,
  applyPatchApproval: CodexSchema.ApplyPatchApprovalResponse,
  execCommandApproval: CodexSchema.ExecCommandApprovalResponse,
} as const;

export const SERVER_NOTIFICATION_PARAMS = {
  error: CodexSchema.V2ErrorNotification,
  "thread/started": CodexSchema.V2ThreadStartedNotification,
  "thread/status/changed": CodexSchema.V2ThreadStatusChangedNotification,
  "thread/archived": CodexSchema.V2ThreadArchivedNotification,
  "thread/deleted": CodexSchema.V2ThreadDeletedNotification,
  "thread/unarchived": CodexSchema.V2ThreadUnarchivedNotification,
  "thread/closed": CodexSchema.V2ThreadClosedNotification,
  "skills/changed": CodexSchema.V2SkillsChangedNotification,
  "thread/name/updated": CodexSchema.V2ThreadNameUpdatedNotification,
  "thread/goal/updated": CodexSchema.V2ThreadGoalUpdatedNotification,
  "thread/goal/cleared": CodexSchema.V2ThreadGoalClearedNotification,
  "thread/environment/connected": CodexSchema.V2EnvironmentConnectionNotification,
  "thread/environment/disconnected": CodexSchema.V2EnvironmentConnectionNotification,
  "thread/settings/updated": CodexSchema.V2ThreadSettingsUpdatedNotification,
  "thread/tokenUsage/updated": CodexSchema.V2ThreadTokenUsageUpdatedNotification,
  "turn/started": CodexSchema.V2TurnStartedNotification,
  "hook/started": CodexSchema.V2HookStartedNotification,
  "turn/completed": CodexSchema.V2TurnCompletedNotification,
  "hook/completed": CodexSchema.V2HookCompletedNotification,
  "turn/diff/updated": CodexSchema.V2TurnDiffUpdatedNotification,
  "turn/plan/updated": CodexSchema.V2TurnPlanUpdatedNotification,
  "item/started": CodexSchema.V2ItemStartedNotification,
  "item/autoApprovalReview/started": CodexSchema.V2ItemGuardianApprovalReviewStartedNotification,
  "item/autoApprovalReview/completed":
    CodexSchema.V2ItemGuardianApprovalReviewCompletedNotification,
  "item/completed": CodexSchema.V2ItemCompletedNotification,
  "rawResponseItem/completed": CodexSchema.V2RawResponseItemCompletedNotification,
  "rawResponse/completed": CodexSchema.V2RawResponseCompletedNotification,
  "item/agentMessage/delta": CodexSchema.V2AgentMessageDeltaNotification,
  "item/plan/delta": CodexSchema.V2PlanDeltaNotification,
  "command/exec/outputDelta": CodexSchema.V2CommandExecOutputDeltaNotification,
  "process/outputDelta": CodexSchema.V2ProcessOutputDeltaNotification,
  "process/exited": CodexSchema.V2ProcessExitedNotification,
  "item/commandExecution/outputDelta": CodexSchema.V2CommandExecutionOutputDeltaNotification,
  "item/commandExecution/terminalInteraction": CodexSchema.V2TerminalInteractionNotification,
  "item/fileChange/outputDelta": CodexSchema.V2FileChangeOutputDeltaNotification,
  "item/fileChange/patchUpdated": CodexSchema.V2FileChangePatchUpdatedNotification,
  "serverRequest/resolved": CodexSchema.V2ServerRequestResolvedNotification,
  "item/mcpToolCall/progress": CodexSchema.V2McpToolCallProgressNotification,
  "mcpServer/oauthLogin/completed": CodexSchema.V2McpServerOauthLoginCompletedNotification,
  "mcpServer/startupStatus/updated": CodexSchema.V2McpServerStatusUpdatedNotification,
  "account/updated": CodexSchema.V2AccountUpdatedNotification,
  "account/rateLimits/updated": CodexSchema.V2AccountRateLimitsUpdatedNotification,
  "app/list/updated": CodexSchema.V2AppListUpdatedNotification,
  "remoteControl/status/changed": CodexSchema.V2RemoteControlStatusChangedNotification,
  "externalAgentConfig/import/progress":
    CodexSchema.V2ExternalAgentConfigImportProgressNotification,
  "externalAgentConfig/import/completed":
    CodexSchema.V2ExternalAgentConfigImportCompletedNotification,
  "fs/changed": CodexSchema.V2FsChangedNotification,
  "item/reasoning/summaryTextDelta": CodexSchema.V2ReasoningSummaryTextDeltaNotification,
  "item/reasoning/summaryPartAdded": CodexSchema.V2ReasoningSummaryPartAddedNotification,
  "item/reasoning/textDelta": CodexSchema.V2ReasoningTextDeltaNotification,
  "thread/compacted": CodexSchema.V2ContextCompactedNotification,
  "model/rerouted": CodexSchema.V2ModelReroutedNotification,
  "model/verification": CodexSchema.V2ModelVerificationNotification,
  "turn/moderationMetadata": CodexSchema.V2TurnModerationMetadataNotification,
  "model/safetyBuffering/updated": CodexSchema.V2ModelSafetyBufferingUpdatedNotification,
  warning: CodexSchema.V2WarningNotification,
  guardianWarning: CodexSchema.V2GuardianWarningNotification,
  deprecationNotice: CodexSchema.V2DeprecationNoticeNotification,
  configWarning: CodexSchema.V2ConfigWarningNotification,
  "fuzzyFileSearch/sessionUpdated": CodexSchema.FuzzyFileSearchSessionUpdatedNotification,
  "fuzzyFileSearch/sessionCompleted": CodexSchema.FuzzyFileSearchSessionCompletedNotification,
  "thread/realtime/started": CodexSchema.V2ThreadRealtimeStartedNotification,
  "thread/realtime/itemAdded": CodexSchema.V2ThreadRealtimeItemAddedNotification,
  "thread/realtime/transcript/delta": CodexSchema.V2ThreadRealtimeTranscriptDeltaNotification,
  "thread/realtime/transcript/done": CodexSchema.V2ThreadRealtimeTranscriptDoneNotification,
  "thread/realtime/outputAudio/delta": CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification,
  "thread/realtime/sdp": CodexSchema.V2ThreadRealtimeSdpNotification,
  "thread/realtime/error": CodexSchema.V2ThreadRealtimeErrorNotification,
  "thread/realtime/closed": CodexSchema.V2ThreadRealtimeClosedNotification,
  "windows/worldWritableWarning": CodexSchema.V2WindowsWorldWritableWarningNotification,
  "windowsSandbox/setupCompleted": CodexSchema.V2WindowsSandboxSetupCompletedNotification,
  "account/login/completed": CodexSchema.V2AccountLoginCompletedNotification,
} as const;
